function fx = d_zvc_d_x(x,y,mu,C)
%D_ZVC_D_X
%    FX = D_ZVC_D_X(X,Y,MU,C)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    01-Jul-2020 14:54:52

t2 = mu.*2.0;
t3 = x.*2.0;
t4 = y.^2;
fx = t3+((t2+t3).*1.0./(t4+(mu+x).^2).^(3.0./2.0).*(t2-2.0))./2.0-mu.*1.0./(t4+(mu+x-1.0).^2).^(3.0./2.0).*(t2+t3-2.0);
